#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootStrapTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MC_Help")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Help_Topic_Tag(tbl_Help_Topic_Tag instance);
    partial void Updatetbl_Help_Topic_Tag(tbl_Help_Topic_Tag instance);
    partial void Deletetbl_Help_Topic_Tag(tbl_Help_Topic_Tag instance);
    partial void Inserttbl_Help_Category(tbl_Help_Category instance);
    partial void Updatetbl_Help_Category(tbl_Help_Category instance);
    partial void Deletetbl_Help_Category(tbl_Help_Category instance);
    partial void Inserttbl_Help_Topic(tbl_Help_Topic instance);
    partial void Updatetbl_Help_Topic(tbl_Help_Topic instance);
    partial void Deletetbl_Help_Topic(tbl_Help_Topic instance);
    partial void Inserttbl_Help_Topic_Related(tbl_Help_Topic_Related instance);
    partial void Updatetbl_Help_Topic_Related(tbl_Help_Topic_Related instance);
    partial void Deletetbl_Help_Topic_Related(tbl_Help_Topic_Related instance);
    #endregion
		
		public dbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MC_HelpConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Help_Topic_Tag> tbl_Help_Topic_Tags
		{
			get
			{
				return this.GetTable<tbl_Help_Topic_Tag>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Help_Category> tbl_Help_Categories
		{
			get
			{
				return this.GetTable<tbl_Help_Category>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Help_Topic> tbl_Help_Topics
		{
			get
			{
				return this.GetTable<tbl_Help_Topic>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Help_Topic_Related> tbl_Help_Topic_Relateds
		{
			get
			{
				return this.GetTable<tbl_Help_Topic_Related>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Help_Topic_Tag")]
	public partial class tbl_Help_Topic_Tag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Help_Topic_Tag_ID;
		
		private int _Help_Topic_ID;
		
		private string _Help_Topic_Tag_Text;
		
		private EntityRef<tbl_Help_Topic> _tbl_Help_Topic;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHelp_Topic_Tag_IDChanging(int value);
    partial void OnHelp_Topic_Tag_IDChanged();
    partial void OnHelp_Topic_IDChanging(int value);
    partial void OnHelp_Topic_IDChanged();
    partial void OnHelp_Topic_Tag_TextChanging(string value);
    partial void OnHelp_Topic_Tag_TextChanged();
    #endregion
		
		public tbl_Help_Topic_Tag()
		{
			this._tbl_Help_Topic = default(EntityRef<tbl_Help_Topic>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_Tag_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Help_Topic_Tag_ID
		{
			get
			{
				return this._Help_Topic_Tag_ID;
			}
			set
			{
				if ((this._Help_Topic_Tag_ID != value))
				{
					this.OnHelp_Topic_Tag_IDChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_Tag_ID = value;
					this.SendPropertyChanged("Help_Topic_Tag_ID");
					this.OnHelp_Topic_Tag_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_ID", DbType="Int NOT NULL")]
		public int Help_Topic_ID
		{
			get
			{
				return this._Help_Topic_ID;
			}
			set
			{
				if ((this._Help_Topic_ID != value))
				{
					if (this._tbl_Help_Topic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHelp_Topic_IDChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_ID = value;
					this.SendPropertyChanged("Help_Topic_ID");
					this.OnHelp_Topic_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_Tag_Text", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Help_Topic_Tag_Text
		{
			get
			{
				return this._Help_Topic_Tag_Text;
			}
			set
			{
				if ((this._Help_Topic_Tag_Text != value))
				{
					this.OnHelp_Topic_Tag_TextChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_Tag_Text = value;
					this.SendPropertyChanged("Help_Topic_Tag_Text");
					this.OnHelp_Topic_Tag_TextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Help_Topic_tbl_Help_Topic_Tag", Storage="_tbl_Help_Topic", ThisKey="Help_Topic_ID", OtherKey="Help_Topic_ID", IsForeignKey=true)]
		public tbl_Help_Topic tbl_Help_Topic
		{
			get
			{
				return this._tbl_Help_Topic.Entity;
			}
			set
			{
				tbl_Help_Topic previousValue = this._tbl_Help_Topic.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Help_Topic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Help_Topic.Entity = null;
						previousValue.tbl_Help_Topic_Tags.Remove(this);
					}
					this._tbl_Help_Topic.Entity = value;
					if ((value != null))
					{
						value.tbl_Help_Topic_Tags.Add(this);
						this._Help_Topic_ID = value.Help_Topic_ID;
					}
					else
					{
						this._Help_Topic_ID = default(int);
					}
					this.SendPropertyChanged("tbl_Help_Topic");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Help_Category")]
	public partial class tbl_Help_Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Help_Category_ID;
		
		private string _Help_Category_Name;
		
		private int _Help_Category_Order;
		
		private System.Nullable<int> _Help_Category_Parent_ID;
		
		private bool _Help_Category_Logged_Out_Available;
		
		private EntitySet<tbl_Help_Topic> _tbl_Help_Topics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHelp_Category_IDChanging(int value);
    partial void OnHelp_Category_IDChanged();
    partial void OnHelp_Category_NameChanging(string value);
    partial void OnHelp_Category_NameChanged();
    partial void OnHelp_Category_OrderChanging(int value);
    partial void OnHelp_Category_OrderChanged();
    partial void OnHelp_Category_Parent_IDChanging(System.Nullable<int> value);
    partial void OnHelp_Category_Parent_IDChanged();
    partial void OnHelp_Category_Logged_Out_AvailableChanging(bool value);
    partial void OnHelp_Category_Logged_Out_AvailableChanged();
    #endregion
		
		public tbl_Help_Category()
		{
			this._tbl_Help_Topics = new EntitySet<tbl_Help_Topic>(new Action<tbl_Help_Topic>(this.attach_tbl_Help_Topics), new Action<tbl_Help_Topic>(this.detach_tbl_Help_Topics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Category_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Help_Category_ID
		{
			get
			{
				return this._Help_Category_ID;
			}
			set
			{
				if ((this._Help_Category_ID != value))
				{
					this.OnHelp_Category_IDChanging(value);
					this.SendPropertyChanging();
					this._Help_Category_ID = value;
					this.SendPropertyChanged("Help_Category_ID");
					this.OnHelp_Category_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Category_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Help_Category_Name
		{
			get
			{
				return this._Help_Category_Name;
			}
			set
			{
				if ((this._Help_Category_Name != value))
				{
					this.OnHelp_Category_NameChanging(value);
					this.SendPropertyChanging();
					this._Help_Category_Name = value;
					this.SendPropertyChanged("Help_Category_Name");
					this.OnHelp_Category_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Category_Order", DbType="Int NOT NULL")]
		public int Help_Category_Order
		{
			get
			{
				return this._Help_Category_Order;
			}
			set
			{
				if ((this._Help_Category_Order != value))
				{
					this.OnHelp_Category_OrderChanging(value);
					this.SendPropertyChanging();
					this._Help_Category_Order = value;
					this.SendPropertyChanged("Help_Category_Order");
					this.OnHelp_Category_OrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Category_Parent_ID", DbType="Int")]
		public System.Nullable<int> Help_Category_Parent_ID
		{
			get
			{
				return this._Help_Category_Parent_ID;
			}
			set
			{
				if ((this._Help_Category_Parent_ID != value))
				{
					this.OnHelp_Category_Parent_IDChanging(value);
					this.SendPropertyChanging();
					this._Help_Category_Parent_ID = value;
					this.SendPropertyChanged("Help_Category_Parent_ID");
					this.OnHelp_Category_Parent_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Category_Logged_Out_Available", DbType="Bit NOT NULL")]
		public bool Help_Category_Logged_Out_Available
		{
			get
			{
				return this._Help_Category_Logged_Out_Available;
			}
			set
			{
				if ((this._Help_Category_Logged_Out_Available != value))
				{
					this.OnHelp_Category_Logged_Out_AvailableChanging(value);
					this.SendPropertyChanging();
					this._Help_Category_Logged_Out_Available = value;
					this.SendPropertyChanged("Help_Category_Logged_Out_Available");
					this.OnHelp_Category_Logged_Out_AvailableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Help_Category_tbl_Help_Topic", Storage="_tbl_Help_Topics", ThisKey="Help_Category_ID", OtherKey="Help_Category_ID")]
		public EntitySet<tbl_Help_Topic> tbl_Help_Topics
		{
			get
			{
				return this._tbl_Help_Topics;
			}
			set
			{
				this._tbl_Help_Topics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Help_Topics(tbl_Help_Topic entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Help_Category = this;
		}
		
		private void detach_tbl_Help_Topics(tbl_Help_Topic entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Help_Category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Help_Topic")]
	public partial class tbl_Help_Topic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Help_Topic_ID;
		
		private string _Help_Topic_Header;
		
		private string _Help_Topic_Text;
		
		private int _Help_Category_ID;
		
		private System.Nullable<int> _Help_Topic_View_Count;
		
		private System.Nullable<int> _Help_Topic_Share_Count;
		
		private System.Nullable<System.DateTime> _Help_Topic_Last_Updated;
		
		private System.Nullable<int> _Help_Topic_Priority;
		
		private bool _Help_Topic_Logged_Out_Available;
		
		private System.Nullable<int> _Help_Topic_Likes;
		
		private System.Nullable<int> _Help_Topic_Dislikes;
		
		private EntitySet<tbl_Help_Topic_Tag> _tbl_Help_Topic_Tags;
		
		private EntitySet<tbl_Help_Topic_Related> _tbl_Help_Topic_Relateds;
		
		private EntitySet<tbl_Help_Topic_Related> _tbl_Help_Topic_Relateds1;
		
		private EntityRef<tbl_Help_Category> _tbl_Help_Category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHelp_Topic_IDChanging(int value);
    partial void OnHelp_Topic_IDChanged();
    partial void OnHelp_Topic_HeaderChanging(string value);
    partial void OnHelp_Topic_HeaderChanged();
    partial void OnHelp_Topic_TextChanging(string value);
    partial void OnHelp_Topic_TextChanged();
    partial void OnHelp_Category_IDChanging(int value);
    partial void OnHelp_Category_IDChanged();
    partial void OnHelp_Topic_View_CountChanging(System.Nullable<int> value);
    partial void OnHelp_Topic_View_CountChanged();
    partial void OnHelp_Topic_Share_CountChanging(System.Nullable<int> value);
    partial void OnHelp_Topic_Share_CountChanged();
    partial void OnHelp_Topic_Last_UpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnHelp_Topic_Last_UpdatedChanged();
    partial void OnHelp_Topic_PriorityChanging(System.Nullable<int> value);
    partial void OnHelp_Topic_PriorityChanged();
    partial void OnHelp_Topic_Logged_Out_AvailableChanging(bool value);
    partial void OnHelp_Topic_Logged_Out_AvailableChanged();
    partial void OnHelp_Topic_LikesChanging(System.Nullable<int> value);
    partial void OnHelp_Topic_LikesChanged();
    partial void OnHelp_Topic_DislikesChanging(System.Nullable<int> value);
    partial void OnHelp_Topic_DislikesChanged();
    #endregion
		
		public tbl_Help_Topic()
		{
			this._tbl_Help_Topic_Tags = new EntitySet<tbl_Help_Topic_Tag>(new Action<tbl_Help_Topic_Tag>(this.attach_tbl_Help_Topic_Tags), new Action<tbl_Help_Topic_Tag>(this.detach_tbl_Help_Topic_Tags));
			this._tbl_Help_Topic_Relateds = new EntitySet<tbl_Help_Topic_Related>(new Action<tbl_Help_Topic_Related>(this.attach_tbl_Help_Topic_Relateds), new Action<tbl_Help_Topic_Related>(this.detach_tbl_Help_Topic_Relateds));
			this._tbl_Help_Topic_Relateds1 = new EntitySet<tbl_Help_Topic_Related>(new Action<tbl_Help_Topic_Related>(this.attach_tbl_Help_Topic_Relateds1), new Action<tbl_Help_Topic_Related>(this.detach_tbl_Help_Topic_Relateds1));
			this._tbl_Help_Category = default(EntityRef<tbl_Help_Category>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Help_Topic_ID
		{
			get
			{
				return this._Help_Topic_ID;
			}
			set
			{
				if ((this._Help_Topic_ID != value))
				{
					this.OnHelp_Topic_IDChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_ID = value;
					this.SendPropertyChanged("Help_Topic_ID");
					this.OnHelp_Topic_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_Header", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Help_Topic_Header
		{
			get
			{
				return this._Help_Topic_Header;
			}
			set
			{
				if ((this._Help_Topic_Header != value))
				{
					this.OnHelp_Topic_HeaderChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_Header = value;
					this.SendPropertyChanged("Help_Topic_Header");
					this.OnHelp_Topic_HeaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_Text", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Help_Topic_Text
		{
			get
			{
				return this._Help_Topic_Text;
			}
			set
			{
				if ((this._Help_Topic_Text != value))
				{
					this.OnHelp_Topic_TextChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_Text = value;
					this.SendPropertyChanged("Help_Topic_Text");
					this.OnHelp_Topic_TextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Category_ID", DbType="Int NOT NULL")]
		public int Help_Category_ID
		{
			get
			{
				return this._Help_Category_ID;
			}
			set
			{
				if ((this._Help_Category_ID != value))
				{
					if (this._tbl_Help_Category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHelp_Category_IDChanging(value);
					this.SendPropertyChanging();
					this._Help_Category_ID = value;
					this.SendPropertyChanged("Help_Category_ID");
					this.OnHelp_Category_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_View_Count", DbType="Int")]
		public System.Nullable<int> Help_Topic_View_Count
		{
			get
			{
				return this._Help_Topic_View_Count;
			}
			set
			{
				if ((this._Help_Topic_View_Count != value))
				{
					this.OnHelp_Topic_View_CountChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_View_Count = value;
					this.SendPropertyChanged("Help_Topic_View_Count");
					this.OnHelp_Topic_View_CountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_Share_Count", DbType="Int")]
		public System.Nullable<int> Help_Topic_Share_Count
		{
			get
			{
				return this._Help_Topic_Share_Count;
			}
			set
			{
				if ((this._Help_Topic_Share_Count != value))
				{
					this.OnHelp_Topic_Share_CountChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_Share_Count = value;
					this.SendPropertyChanged("Help_Topic_Share_Count");
					this.OnHelp_Topic_Share_CountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_Last_Updated", DbType="Date")]
		public System.Nullable<System.DateTime> Help_Topic_Last_Updated
		{
			get
			{
				return this._Help_Topic_Last_Updated;
			}
			set
			{
				if ((this._Help_Topic_Last_Updated != value))
				{
					this.OnHelp_Topic_Last_UpdatedChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_Last_Updated = value;
					this.SendPropertyChanged("Help_Topic_Last_Updated");
					this.OnHelp_Topic_Last_UpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_Priority", DbType="Int")]
		public System.Nullable<int> Help_Topic_Priority
		{
			get
			{
				return this._Help_Topic_Priority;
			}
			set
			{
				if ((this._Help_Topic_Priority != value))
				{
					this.OnHelp_Topic_PriorityChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_Priority = value;
					this.SendPropertyChanged("Help_Topic_Priority");
					this.OnHelp_Topic_PriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_Logged_Out_Available", DbType="Bit NOT NULL")]
		public bool Help_Topic_Logged_Out_Available
		{
			get
			{
				return this._Help_Topic_Logged_Out_Available;
			}
			set
			{
				if ((this._Help_Topic_Logged_Out_Available != value))
				{
					this.OnHelp_Topic_Logged_Out_AvailableChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_Logged_Out_Available = value;
					this.SendPropertyChanged("Help_Topic_Logged_Out_Available");
					this.OnHelp_Topic_Logged_Out_AvailableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_Likes", DbType="Int")]
		public System.Nullable<int> Help_Topic_Likes
		{
			get
			{
				return this._Help_Topic_Likes;
			}
			set
			{
				if ((this._Help_Topic_Likes != value))
				{
					this.OnHelp_Topic_LikesChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_Likes = value;
					this.SendPropertyChanged("Help_Topic_Likes");
					this.OnHelp_Topic_LikesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_Dislikes", DbType="Int")]
		public System.Nullable<int> Help_Topic_Dislikes
		{
			get
			{
				return this._Help_Topic_Dislikes;
			}
			set
			{
				if ((this._Help_Topic_Dislikes != value))
				{
					this.OnHelp_Topic_DislikesChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_Dislikes = value;
					this.SendPropertyChanged("Help_Topic_Dislikes");
					this.OnHelp_Topic_DislikesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Help_Topic_tbl_Help_Topic_Tag", Storage="_tbl_Help_Topic_Tags", ThisKey="Help_Topic_ID", OtherKey="Help_Topic_ID")]
		public EntitySet<tbl_Help_Topic_Tag> tbl_Help_Topic_Tags
		{
			get
			{
				return this._tbl_Help_Topic_Tags;
			}
			set
			{
				this._tbl_Help_Topic_Tags.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Help_Topic_tbl_Help_Topic_Related", Storage="_tbl_Help_Topic_Relateds", ThisKey="Help_Topic_ID", OtherKey="Help_Topic_ID_First")]
		public EntitySet<tbl_Help_Topic_Related> tbl_Help_Topic_Relateds
		{
			get
			{
				return this._tbl_Help_Topic_Relateds;
			}
			set
			{
				this._tbl_Help_Topic_Relateds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Help_Topic_tbl_Help_Topic_Related1", Storage="_tbl_Help_Topic_Relateds1", ThisKey="Help_Topic_ID", OtherKey="Help_Topic_ID_Second")]
		public EntitySet<tbl_Help_Topic_Related> tbl_Help_Topic_Relateds1
		{
			get
			{
				return this._tbl_Help_Topic_Relateds1;
			}
			set
			{
				this._tbl_Help_Topic_Relateds1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Help_Category_tbl_Help_Topic", Storage="_tbl_Help_Category", ThisKey="Help_Category_ID", OtherKey="Help_Category_ID", IsForeignKey=true)]
		public tbl_Help_Category tbl_Help_Category
		{
			get
			{
				return this._tbl_Help_Category.Entity;
			}
			set
			{
				tbl_Help_Category previousValue = this._tbl_Help_Category.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Help_Category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Help_Category.Entity = null;
						previousValue.tbl_Help_Topics.Remove(this);
					}
					this._tbl_Help_Category.Entity = value;
					if ((value != null))
					{
						value.tbl_Help_Topics.Add(this);
						this._Help_Category_ID = value.Help_Category_ID;
					}
					else
					{
						this._Help_Category_ID = default(int);
					}
					this.SendPropertyChanged("tbl_Help_Category");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Help_Topic_Tags(tbl_Help_Topic_Tag entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Help_Topic = this;
		}
		
		private void detach_tbl_Help_Topic_Tags(tbl_Help_Topic_Tag entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Help_Topic = null;
		}
		
		private void attach_tbl_Help_Topic_Relateds(tbl_Help_Topic_Related entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Help_Topic = this;
		}
		
		private void detach_tbl_Help_Topic_Relateds(tbl_Help_Topic_Related entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Help_Topic = null;
		}
		
		private void attach_tbl_Help_Topic_Relateds1(tbl_Help_Topic_Related entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Help_Topic1 = this;
		}
		
		private void detach_tbl_Help_Topic_Relateds1(tbl_Help_Topic_Related entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Help_Topic1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Help_Topic_Related")]
	public partial class tbl_Help_Topic_Related : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Help_Topic_Related_ID;
		
		private int _Help_Topic_ID_First;
		
		private int _Help_Topic_ID_Second;
		
		private EntityRef<tbl_Help_Topic> _tbl_Help_Topic;
		
		private EntityRef<tbl_Help_Topic> _tbl_Help_Topic1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHelp_Topic_Related_IDChanging(int value);
    partial void OnHelp_Topic_Related_IDChanged();
    partial void OnHelp_Topic_ID_FirstChanging(int value);
    partial void OnHelp_Topic_ID_FirstChanged();
    partial void OnHelp_Topic_ID_SecondChanging(int value);
    partial void OnHelp_Topic_ID_SecondChanged();
    #endregion
		
		public tbl_Help_Topic_Related()
		{
			this._tbl_Help_Topic = default(EntityRef<tbl_Help_Topic>);
			this._tbl_Help_Topic1 = default(EntityRef<tbl_Help_Topic>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_Related_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Help_Topic_Related_ID
		{
			get
			{
				return this._Help_Topic_Related_ID;
			}
			set
			{
				if ((this._Help_Topic_Related_ID != value))
				{
					this.OnHelp_Topic_Related_IDChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_Related_ID = value;
					this.SendPropertyChanged("Help_Topic_Related_ID");
					this.OnHelp_Topic_Related_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_ID_First", DbType="Int NOT NULL")]
		public int Help_Topic_ID_First
		{
			get
			{
				return this._Help_Topic_ID_First;
			}
			set
			{
				if ((this._Help_Topic_ID_First != value))
				{
					if (this._tbl_Help_Topic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHelp_Topic_ID_FirstChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_ID_First = value;
					this.SendPropertyChanged("Help_Topic_ID_First");
					this.OnHelp_Topic_ID_FirstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Help_Topic_ID_Second", DbType="Int NOT NULL")]
		public int Help_Topic_ID_Second
		{
			get
			{
				return this._Help_Topic_ID_Second;
			}
			set
			{
				if ((this._Help_Topic_ID_Second != value))
				{
					if (this._tbl_Help_Topic1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHelp_Topic_ID_SecondChanging(value);
					this.SendPropertyChanging();
					this._Help_Topic_ID_Second = value;
					this.SendPropertyChanged("Help_Topic_ID_Second");
					this.OnHelp_Topic_ID_SecondChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Help_Topic_tbl_Help_Topic_Related", Storage="_tbl_Help_Topic", ThisKey="Help_Topic_ID_First", OtherKey="Help_Topic_ID", IsForeignKey=true)]
		public tbl_Help_Topic tbl_Help_Topic
		{
			get
			{
				return this._tbl_Help_Topic.Entity;
			}
			set
			{
				tbl_Help_Topic previousValue = this._tbl_Help_Topic.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Help_Topic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Help_Topic.Entity = null;
						previousValue.tbl_Help_Topic_Relateds.Remove(this);
					}
					this._tbl_Help_Topic.Entity = value;
					if ((value != null))
					{
						value.tbl_Help_Topic_Relateds.Add(this);
						this._Help_Topic_ID_First = value.Help_Topic_ID;
					}
					else
					{
						this._Help_Topic_ID_First = default(int);
					}
					this.SendPropertyChanged("tbl_Help_Topic");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Help_Topic_tbl_Help_Topic_Related1", Storage="_tbl_Help_Topic1", ThisKey="Help_Topic_ID_Second", OtherKey="Help_Topic_ID", IsForeignKey=true)]
		public tbl_Help_Topic tbl_Help_Topic1
		{
			get
			{
				return this._tbl_Help_Topic1.Entity;
			}
			set
			{
				tbl_Help_Topic previousValue = this._tbl_Help_Topic1.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Help_Topic1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Help_Topic1.Entity = null;
						previousValue.tbl_Help_Topic_Relateds1.Remove(this);
					}
					this._tbl_Help_Topic1.Entity = value;
					if ((value != null))
					{
						value.tbl_Help_Topic_Relateds1.Add(this);
						this._Help_Topic_ID_Second = value.Help_Topic_ID;
					}
					else
					{
						this._Help_Topic_ID_Second = default(int);
					}
					this.SendPropertyChanged("tbl_Help_Topic1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
